### ISSUE TITLE
Evolving_Boxes-master/lib/pycocotools/_mask.pyx' make: *** [all] Error 1

### ISSUE THREAD

**Issue by ubenz55555** [Willy0919/Evovling_Boxes#1]
Hi ! I'm facing an error when I type "make" in /lib directory, get these line on terminal

test2@test2-VirtualBox:~/envolvingbox/Evolving_Boxes-master/lib$ make all
python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
cythoning pycocotools/_mask.pyx to pycocotools/_mask.c
error: [Errno 2] No such file or directory: '/home/test2/envolvingbox/Evolving_Boxes-master/lib/pycocotools/_mask.pyx'
make: *** [all] Error 1

Can somebody help me? Thanks !

**Comment by ubenz55555** [comment]
Compare to rbgirshick/py-faster-rcnn , there is a folder called "pycocotools" under /lib by default , but this code doesn't  have it by default . It will  generate a new folder "pycocotools" which is empty after I type "make" under /lib . The terminal will return a error message just like above. 
My first solution is go to rbgirshick/py-faster-rcnn github website , download everything under "pycocotools" folder , and type "make " again. This time it returns another error:

test2@test2-VirtualBox:~/envolvingbox/Evolving_Boxes-master/lib$ make all
python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
cythoning pycocotools/_mask.pyx to pycocotools/_mask.c
warning: pycocotools/_mask.pyx:1:0: Unreachable code
Error compiling Cython file:
------------------------------------------------------------
...
        objs = frPoly(pyobj, h, w )
    elif type(pyobj) == list and type(pyobj[0]) == dict:
        objs = frUncompressedRLE(pyobj, h, w)
    else:
        raise Exception('input type is not supported.')
return objs
^


pycocotools/_mask.pyx:291:0: Return not inside a function body
building 'pycocotools._mask' extension
creating build/temp.linux-x86_64-2.7/pycocotools
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -Ipycocotools -I/usr/include/python2.7 -c pycocotools/maskApi.c -o build/temp.linux-x86_64-2.7/pycocotools/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -Ipycocotools -I/usr/include/python2.7 -c pycocotools/_mask.c -o build/temp.linux-x86_64-2.7/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
pycocotools/_mask.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make: *** [all] Error 1
------------------------------------------------------------

Thanks!

**Comment by Willy0919** [comment]
Thank you for pointing out mistakes in our codes, I have fixed the setup.py, you can try it again now.

**Comment by Willy0919** [comment]
Thank you for pointing out mistakes in our codes, I have fixed the setup.py, you can try it again now. @ubenz55555

**Comment by ubenz55555** [comment]
Hello:

   I have arranged the setup.py and "make" again, the terminal shows as folloing 
test2@test2-VirtualBox:~/envolvingbox/Evolving_Boxes-master/lib$ make
python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
rm -rf build


Is this the correct one ? Thank you for your reply :)

**Comment by Willy0919** [comment]
If you can see the *.so in directory lib/nms/ and lib/utils/ , then you can try the demo.py to test if it is right. @ubenz55555
