### ISSUE TITLE
File "train_net.py", line 19, in <module>     from datasets.factory import get_imdb ImportError: No module named datasets.factory

### ISSUE THREAD

**Issue by ubenz55555** [Willy0919/Evovling_Boxes#2]
Hi 

    I have another problem when I type "python train_net.py" under /tools , it shows up 

File "train_net.py", line 19, in <module>
    from datasets.factory import get_imdb
ImportError: No module named datasets.factory

I had compare with the faster rcnn github code with your code, but still can't find out where is wrong ?

Thank you very much !

**Comment by z362194037** [comment]
all you need to do is to add a` __init__.py` in the datasets folder
