### ISSUE TITLE
can't run test.sh

### ISSUE THREAD

**Issue by sezan92** [Willy0919/Evovling_Boxes#5]
Hello, I have built the caffe-fast-rcnn ,and then built in lib folder .. but whenever i try to run test.sh , it shows me this error 
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 658:21: Message type "caffe.LayerParameter" has no field named "roi_pooling_param".
F0706 20:17:45.385499 21175 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/detrac/VGG16/test_1-3-5.prototxt

**Comment by JasonZhao001** [comment]
I have the same problem, is there anyone has an idea to solve it ?

**Comment by sezan92** [comment]
It has a lot of problems bro.. although i have solved this one .. I am writting another post on the issues

**Comment by Willy0919** [comment]
@sezan92 @JasonZhao001  This may be the problem of caffe version which doesn't contain definition of "roi_pooling_param", I have replaced the caffe branch so that you can solve this problem.
