### ISSUE TITLE
A Lot of problems with this repo. 

### ISSUE THREAD

**Issue by sezan92** [Willy0919/Evovling_Boxes#6]
1) First of all a directory didn't have __init__.py file to include it in the python code .. I added it

2) the lib folder in the had to be compiled before running the demo code , you didn't mention it 

3) most importantly , you provided a folder "caffe-fast-rcnn". the branch they provided isn't compatible with the project. because the project needs some files like roi-pooling-layer ..the branch they provided, didn't have this source file! so i had to figure out the real branch 

4 I noticed that your work  is based on another github repository named py-fast-rcnn.

5) i tried that github repository . that repository got installed and the demo file they provided worked.

6) then i replaced the caffe-fast-rcnn of evolving boxes with that of py-faster-rcnn and it has all the necessary files.
the repo has been built. 

I myself solved all of these problems. But I am facing another problem which I am unable to solve. Whenever I try to run the demo code, I get this error, 

"IndexError: only integers, slices (:), ellipsis (...), numpy.newaxis (None) and integer or boolean arrays are valid indices" 

I tried to write my own code , still this error is coming up. Can you help me ? which numpy version did you use ? is it because of numpy upgrading ? Please help

**Comment by JasonZhao001** [comment]
I met the same final problem too. @Willy0919

**Comment by Willy0919** [comment]
@sezan92 @JasonZhao001 
The numpy version was 1.11.2 when running my released codes, so I didn't encounter this problem. After I update my numpy version to 1.13.1, it has the same problem, so you can modify the codes in concat_test.py and concat.py:
`top[0].data[self.selectDim,0:self.Dim1] = (fc1[self.keep1.tolist()])[self.keep2[self.selectDim].tolist()]`
to:
`top[0].data[self.selectDim,0:self.Dim1] = (fc1[self.keep1.astype(int).tolist()])[self.keep2[self.selectDim].astype(int).tolist()]`
which can solve the problem.

**Comment by 20143698lhy** [comment]
Hello , can you remember the solutions of problems  you mentioned above ? I meet the same problem 1/2/3 , and i can't solve the issue 3 , looking forward to your apply , thanks! @sezan92
